decks = {
    "ESP48": {
        "O01": {"literal": "As de Oros", "value": 1, "priority": 4, "real_value": 1}, #Oros
        "O02": {"literal": "Dos de Oros", "value": 2, "priority": 4, "real_value": 2},
        "O03": {"literal": "Tres de Oros", "value": 3, "priority": 4, "real_value": 3},
        "O04": {"literal": "Cuatro de Oros", "value": 4, "priority": 4, "real_value": 4},
        "O05": {"literal": "Cinco de Oros", "value": 5, "priority": 4, "real_value": 5},
        "O06": {"literal": "Seis de Oros", "value": 6, "priority": 4, "real_value": 6},
        "O07": {"literal": "Siete de Oros", "value": 7, "priority": 4, "real_value": 7},
        "O08": {"literal": "Ocho de Oros", "value": 8, "priority": 4, "real_value": 0.5}, 
        "O09": {"literal": "Nueve de Oros", "value": 9, "priority": 4, "real_value": 0.5},
        "O10": {"literal": "Sota de Oros", "value": 10, "priority": 4, "real_value": 0.5},
        "O11": {"literal": "Caballo de Oros", "value": 11, "priority": 4, "real_value": 0.5},
        "O12": {"literal": "Rey de Oros", "value": 12, "priority": 4, "real_value": 0.5},

        "C01": {"literal": "As de Copas", "value": 1, "priority": 3, "real_value": 1}, #Copas
        "C02": {"literal": "Dos de Copas", "value": 2, "priority": 3, "real_value": 2},
        "C03": {"literal": "Tres de Copas", "value": 3, "priority": 3, "real_value": 3},
        "C04": {"literal": "Cuatro de Copas", "value": 4, "priority": 3, "real_value": 4},
        "C05": {"literal": "Cinco de Copas", "value": 5, "priority": 3, "real_value": 5},
        "C06": {"literal": "Seis de Copas", "value": 6, "priority": 3, "real_value": 6},
        "C07": {"literal": "Siete de Copas", "value": 7, "priority": 3, "real_value": 7},
        "C08": {"literal": "Ocho de Copas", "value": 8, "priority": 3, "real_value": 0.5},
        "C09": {"literal": "Nueve de Copas", "value": 9, "priority": 3, "real_value": 0.5},
        "C10": {"literal": "Sota de Copas", "value": 10, "priority": 3, "real_value": 0.5},
        "C11": {"literal": "Caballo de Copas", "value": 11, "priority": 3, "real_value": 0.5},
        "C12": {"literal": "Rey de Copas", "value": 12, "priority": 3, "real_value": 0.5},

        "E01": {"literal": "As de Espadas", "value": 1, "priority": 2, "real_value": 1}, #Espadas
        "E02": {"literal": "Dos de Espadas", "value": 2, "priority": 2, "real_value": 2},
        "E03": {"literal": "Tres de Espadas", "value": 3, "priority": 2, "real_value": 3},
        "E04": {"literal": "Cuatro de Espadas", "value": 4, "priority": 2, "real_value": 4},
        "E05": {"literal": "Cinco de Espadas", "value": 5, "priority": 2, "real_value": 5},
        "E06": {"literal": "Seis de Espadas", "value": 6, "priority": 2, "real_value": 6},
        "E07": {"literal": "Siete de Espadas", "value": 7, "priority": 2, "real_value": 7},
        "E08": {"literal": "Ocho de Espadas", "value": 8, "priority": 2, "real_value": 0.5},
        "E09": {"literal": "Nueve de Espadas", "value": 9, "priority": 2, "real_value": 0.5},
        "E10": {"literal": "Sota de Espadas", "value": 10, "priority": 2, "real_value": 0.5},
        "E11": {"literal": "Caballo de Espadas", "value": 11, "priority": 2, "real_value": 0.5},
        "E12": {"literal": "Rey de Espadas", "value": 12, "priority": 2, "real_value": 0.5},

        "B01": {"literal": "As de Bastos", "value": 1, "priority": 1, "real_value": 1}, #Bastos
        "B02": {"literal": "Dos de Bastos", "value": 2, "priority": 1, "real_value": 2},
        "B03": {"literal": "Tres de Bastos", "value": 3, "priority": 1, "real_value": 3},
        "B04": {"literal": "Cuatro de Bastos", "value": 4, "priority": 1, "real_value": 4},
        "B05": {"literal": "Cinco de Bastos", "value": 5, "priority": 1, "real_value": 5},
        "B06": {"literal": "Seis de Bastos", "value": 6, "priority": 1, "real_value": 6},
        "B07": {"literal": "Siete de Bastos", "value": 7, "priority": 1, "real_value": 7},
        "B08": {"literal": "Ocho de Bastos", "value": 8, "priority": 1, "real_value": 0.5},
        "B09": {"literal": "Nueve de Bastos", "value": 9, "priority": 1, "real_value": 0.5},
        "B10": {"literal": "Sota de Bastos", "value": 10, "priority": 1, "real_value": 0.5},
        "B11": {"literal": "Caballo de Bastos", "value": 11, "priority": 1, "real_value": 0.5},
        "B12": {"literal": "Rey de Bastos", "value": 12, "priority": 1, "real_value": 0.5},
    },

    "ESP40": {
        "O01": {"literal": "As de Oros", "value": 1, "priority": 4, "real_value": 1}, #Oros
        "O02": {"literal": "Dos de Oros", "value": 2, "priority": 4, "real_value": 2},
        "O03": {"literal": "Tres de Oros", "value": 3, "priority": 4, "real_value": 3},
        "O04": {"literal": "Cuatro de Oros", "value": 4, "priority": 4, "real_value": 4},
        "O05": {"literal": "Cinco de Oros", "value": 5, "priority": 4, "real_value": 5},
        "O06": {"literal": "Seis de Oros", "value": 6, "priority": 4, "real_value": 6},
        "O07": {"literal": "Siete de Oros", "value": 7, "priority": 4, "real_value": 7},
        "O08": {"literal": "Sota de Oros", "value": 10, "priority": 4, "real_value": 0.5},
        "O09": {"literal": "Caballo de Oros", "value": 11, "priority": 4, "real_value": 0.5},
        "O10": {"literal": "Rey de Oros", "value": 12, "priority": 4, "real_value": 0.5},

        "C01": {"literal": "As de Copas", "value": 1, "priority": 3, "real_value": 1}, #Copas
        "C02": {"literal": "Dos de Copas", "value": 2, "priority": 3, "real_value": 2},
        "C03": {"literal": "Tres de Copas", "value": 3, "priority": 3, "real_value": 3},
        "C04": {"literal": "Cuatro de Copas", "value": 4, "priority": 3, "real_value": 4},
        "C05": {"literal": "Cinco de Copas", "value": 5, "priority": 3, "real_value": 5},
        "C06": {"literal": "Seis de Copas", "value": 6, "priority": 3, "real_value": 6},
        "C07": {"literal": "Siete de Copas", "value": 7, "priority": 3, "real_value": 7},
        "C08": {"literal": "Sota de Copas", "value": 10, "priority": 3, "real_value": 0.5},
        "C09": {"literal": "Caballo de Copas", "value": 11, "priority": 3, "real_value": 0.5},
        "C10": {"literal": "Rey de Copas", "value": 12, "priority": 3, "real_value": 0.5},

        "E01": {"literal": "As de Espadas", "value": 1, "priority": 2, "real_value": 1}, #Espadas
        "E02": {"literal": "Dos de Espadas", "value": 2, "priority": 2, "real_value": 2},
        "E03": {"literal": "Tres de Espadas", "value": 3, "priority": 2, "real_value": 3},
        "E04": {"literal": "Cuatro de Espadas", "value": 4, "priority": 2, "real_value": 4},
        "E05": {"literal": "Cinco de Espadas", "value": 5, "priority": 2, "real_value": 5},
        "E06": {"literal": "Seis de Espadas", "value": 6, "priority": 2, "real_value": 6},
        "E07": {"literal": "Siete de Espadas", "value": 7, "priority": 2, "real_value": 7},
        "E08": {"literal": "Sota de Espadas", "value": 10, "priority": 2, "real_value": 0.5},
        "E09": {"literal": "Caballo de Espadas", "value": 11, "priority": 2, "real_value": 0.5},
        "E10": {"literal": "Rey de Espadas", "value": 12, "priority": 2, "real_value": 0.5},

        "B01": {"literal": "As de Bastos", "value": 1, "priority": 1, "real_value": 1}, #Bastos
        "B02": {"literal": "Dos de Bastos", "value": 2, "priority": 1, "real_value": 2},
        "B03": {"literal": "Tres de Bastos", "value": 3, "priority": 1, "real_value": 3},
        "B04": {"literal": "Cuatro de Bastos", "value": 4, "priority": 1, "real_value": 4},
        "B05": {"literal": "Cinco de Bastos", "value": 5, "priority": 1, "real_value": 5},
        "B06": {"literal": "Seis de Bastos", "value": 6, "priority": 1, "real_value": 6},
        "B07": {"literal": "Siete de Bastos", "value": 7, "priority": 1, "real_value": 7},
        "B08": {"literal": "Sota de Bastos", "value": 10, "priority": 1, "real_value": 0.5},
        "B09": {"literal": "Caballo de Bastos", "value": 11, "priority": 1, "real_value": 0.5},
        "B10": {"literal": "Rey de Bastos", "value": 12, "priority": 1, "real_value": 0.5},
    },

    "Poker": {
        "D01": {"literal": "Ace of Diamonds", "value": 1, "priority": 4, "real_value": 1}, #Diamonds
        "D02": {"literal": "Deuce of Diamonds", "value": 2, "priority": 4, "real_value": 2},
        "D03": {"literal": "Three of Diamonds", "value": 3, "priority": 4, "real_value": 3},
        "D04": {"literal": "Four of Diamonds", "value": 4, "priority": 4, "real_value": 4},
        "D05": {"literal": "Five of Diamonds", "value": 5, "priority": 4, "real_value": 5},
        "D06": {"literal": "Six of Diamonds", "value": 6, "priority": 4, "real_value": 6},
        "D07": {"literal": "Seven of Diamonds", "value": 7, "priority": 4, "real_value": 7},
        "D08": {"literal": "Eight of Diamonds", "value": 8, "priority": 4, "real_value": 0.5},
        "D09": {"literal": "Nine of Diamonds", "value": 9, "priority": 4, "real_value": 0.5},
        "D10": {"literal": "Ten of Diamonds", "value": 10, "priority": 4, "real_value": 0.5},
        "D11": {"literal": "Jack of Diamonds", "value": 11, "priority": 4, "real_value": 0.5},
        "D12": {"literal": "Queen of Diamonds", "value": 12, "priority": 4, "real_value": 0.5},
        "D13": {"literal": "King of Diamonds", "value": 13, "priority": 4, "real_value": 0.5},
        
        "H01": {"literal": "Ace of Hearts", "value": 1, "priority": 3, "real_value": 1}, #Hearts
        "H02": {"literal": "Deuce of Hearts", "value": 2, "priority": 3, "real_value": 2},
        "H03": {"literal": "Three of Hearts", "value": 3, "priority": 3, "real_value": 3},
        "H04": {"literal": "Four of Hearts", "value": 4, "priority": 3, "real_value": 4},
        "H05": {"literal": "Five of Hearts", "value": 5, "priority": 3, "real_value": 5},
        "H06": {"literal": "Six of Hearts", "value": 6, "priority": 3, "real_value": 6},
        "H07": {"literal": "Seven of Hearts", "value": 7, "priority": 3, "real_value": 7},
        "H08": {"literal": "Eight of Hearts", "value": 8, "priority": 3, "real_value": 0.5},
        "H09": {"literal": "Nine of Hearts", "value": 9, "priority": 3, "real_value": 0.5},
        "H10": {"literal": "Ten of Hearts", "value": 10, "priority": 3, "real_value": 0.5},
        "H11": {"literal": "Jack of Hearts", "value": 11, "priority": 3, "real_value": 0.5},
        "H12": {"literal": "Queen of Hearts", "value": 12, "priority": 3, "real_value": 0.5},
        "H13": {"literal": "King of Hearts", "value": 13, "priority": 3, "real_value": 0.5},

        "S01": {"literal": "Ace of Spades", "value": 1, "priority": 2, "real_value": 1}, #Spades
        "S02": {"literal": "Deuce of Spades", "value": 2, "priority": 2, "real_value": 2},
        "S03": {"literal": "Three of Spades", "value": 3, "priority": 2, "real_value": 3},
        "S04": {"literal": "Four of Spades", "value": 4, "priority": 2, "real_value": 4},
        "S05": {"literal": "Five of Spades", "value": 5, "priority": 2, "real_value": 5},
        "S06": {"literal": "Six of Spades", "value": 6, "priority": 2, "real_value": 6},
        "S07": {"literal": "Seven of Spades", "value": 7, "priority": 2, "real_value": 7},
        "S08": {"literal": "Eight of Spades", "value": 8, "priority": 2, "real_value": 0.5},
        "S09": {"literal": "Nine of Spades", "value": 9, "priority": 2, "real_value": 0.5},
        "S10": {"literal": "Ten of Spades", "value": 10, "priority": 2, "real_value": 0.5},
        "S11": {"literal": "Jack of Spades", "value": 11, "priority": 2, "real_value": 0.5},
        "S12": {"literal": "Queen of Spades", "value": 12, "priority": 2, "real_value": 0.5},
        "S13": {"literal": "King of Spades", "value": 13, "priority": 2, "real_value": 0.5},

        "T01": {"literal": "Ace of Clubs", "value": 1, "priority": 1, "real_value": 1}, #Clubs
        "T02": {"literal": "Deuce of Clubs", "value": 2, "priority": 1, "real_value": 2},
        "T03": {"literal": "Three of Clubs", "value": 3, "priority": 1, "real_value": 3},
        "T04": {"literal": "Four of Clubs", "value": 4, "priority": 1, "real_value": 4},
        "T05": {"literal": "Five of Clubs", "value": 5, "priority": 1, "real_value": 5},
        "T06": {"literal": "Six of Clubs", "value": 6, "priority": 1, "real_value": 6},
        "T07": {"literal": "Seven of Clubs", "value": 7, "priority": 1, "real_value": 7},
        "T08": {"literal": "Eight of Clubs", "value": 8, "priority": 1, "real_value": 0.5},
        "T09": {"literal": "Nine of Clubs", "value": 9, "priority": 1, "real_value": 0.5},
        "T10": {"literal": "Ten of Clubs", "value": 10, "priority": 1, "real_value": 0.5},
        "T11": {"literal": "Jack of Clubs", "value": 11, "priority": 1, "real_value": 0.5},
        "T12": {"literal": "Queen of Clubs", "value": 12, "priority": 1, "real_value": 0.5},
        "T13": {"literal": "King of Clubs", "value": 13, "priority": 1, "real_value": 0.5}
    } 
}