TEXTS = {
    "option": "Option",
    "option_delete_player": "Option ( -id to remove player [-id11111111J], -1 to exit): ",
    "value_error": " Value must be an Integer ",
    "invalid_option": " Invalid Option ",
    "continue": "Press Enter to Continue",
    "exit": " Goodbye! Thanks for playing! ",
    "invalidDeck": "No deck assigned, select one before starting the game",
    "player_value_changed_ok": " Player value changed correctly! ",
    "player_value_changed_error": " Player key does not exist: ",
    "demand_name": "Introduce your name:\t",
    "error_demand_name": " Incorrect name, please, enter a name not empty with only letters ",
    "demand_nif": "Introduce your NIF:\t",
    "error_demand_nif": " Wrong NIF ",
    "error_duplicated_nif": " NIF Duplicated ",
    "demand_profile": "Select your profile: ",
    "demand_confirmation": "Is it OK? Y/n\t",
    "select_players": " Select Players ",
    "select_players_human": "Human Players",
    "select_players_bot": "Bot Players",
    "select_players_id": " ID",
    "select_players_name": "Name",
    "select_players_type": "Type",
    "player_deleted": " Player deleted successfully! ",
    "demand_max_rounds": "Enter new Max Rounds: ",
    "error_max_rounds": " Max Rounds Has To Be Between 1 and 30 ",
    "setup_max_rounds": " Established maximum of rounds to ",
    "error_init_play_players": " Set the players that compose the game first [2-6] ",
    "error_init_play_deck": " Set the deck of cards first ",
    "report_2_id_game": "ID Game",
    "report_2_id_player": "ID Player",
    "report_2_round": "Round",
    "report_2_max_bet": "Max Bet",
    "report_next_page": "+ to go ahead, exit to go Reports: ",
    "report_next_page_back_page": "+ to go ahead, - to go back , exit to go Reports: ",
    "report_back_page": "- to go back, exit to go Reports: ",
}