TEXTS = {
    "option": "Option",
    "option_delete_player": "Option ( -id to remove player [-id11111111J], -1 to exit): ",
    "value_error": " Value must be an Integer ",
    "invalid_option": " Invalid Option ",
    "continue": "Press Enter to Continue",
    "exit": " Goodbye! Thanks for playing! ",
    "invalidDeck": "No deck assigned, select one before starting the game",
    "player_value_changed_ok": " Player value changed correctly! ",
    "player_value_changed_error": " Player key does not exist: ",
    "demand_human_name": "Enter your name:\t",
    "demand_bot_name": "Enter the bot's name:\t",
    "error_demand_name": " Incorrect name, please enter a non-empty name containing only letters ",
    "demand_nif": "Enter your NIF:\t",
    "bot_nif": "Randomly Generated NIF:\t",
    "error_demand_nif": " Wrong NIF ",
    "error_duplicated_nif": " NIF Duplicated ",
    "demand_human_profile": "Select your profile: ",
    "demand_bot_profile": "Select the bot's profile: ",
    "demand_confirmation": "Is this OK? y/n\t",
    "select_players": " Select Players ",
    "select_players_human": "Human Players",
    "select_players_bot": "Bot Players",
    "select_players_id": " ID",
    "select_players_name": "Name",
    "select_players_type": "Type",
    "player_deleted": " Player deleted successfully! ",
    "demand_max_rounds": "Enter new Max Rounds: ",
    "error_max_rounds": " Max Rounds Has To Be Between 1 and 30 ",
    "setup_max_rounds": " Established maximum of rounds to ",
    "error_init_play_players": " Set the players that compose the game first [2-6] ",
    "error_init_play_deck": " Set the deck of cards first ",
    "report_id_game": "ID Game",
    "report_id_player": "ID Player",
    "report_max_bet": "Max Bet",
    "report_min_bet": "Min Bet",
    "report_rounds": "Rounds",
    "report_avg_bet": "Average Bet",
    "report_avg_bet_first_round": "Average Bet Of First Round",
    "report_avg_bet_last_round": "Average Bet Of Last Round",
    "report_rounds_won": "Rounds Won",
    "report_pce_won": "Win Percentage",
    "report_suit": "Suit",
    "report_initial_card": "Most Repeated Card",
    "report_times_repeated": "Times Repeated",
    "report_games_played": "Games Played",
    "report_points_won": "Points Won",
    "report_user_been_bank": "Users who have been bank",
    "report_exit": "exit to go to Reports: ",
    "ranking_id_player": "Player ID",
    "ranking_name": "Name",
    "ranking_earnings": "Earnings",
    "ranking_games_played": "Games Played",
    "ranking_minutes_played": "Minutes Played",
    "ranking_exit": "exit to go to Rankings: ",
    "query_next_page": "+ to go ahead, ",
    "query_back_page": "- to go back, ",
}